id: c5c5dd30-abcf-46b6-3497-f9a1bba5b700
# Name of the quickstart (required)
slug: apm-logs

# Displayed in the UI (required)
title: APM Logs

# Long-form description of the quickstart (required)
description: |
  This dashboard helps customers keep an eye on APM Logs sent to NR. It will monitor for any dropped logs and/or duplicate logging with the infra agent.

  For more information or support, please go to https://docs.newrelic.com/docs/logs/logs-context/upgrade-to-automatic-logs-context/

# Displayed in search results and recommendations. Summarizes a packs functionality.
summary: |
  Get better insights into your logging data sent by our apm agents.

# Support level: New Relic | Verified | Community (required)
level: New Relic

# Authors of the quickstart (required)
authors:
  - Leon Chapman

# Keywords for filtering / searching criteria in the UI
keywords:
  - logs
  - APM

installPlans:
  - basic-dashboard

documentation:
  - name: New Relic APM Installation Docs
    url: https://docs.newrelic.com/docs/logs/logs-context/upgrade-to-automatic-logs-context/
    description: Configure automatic logs in context with logs

icon: logo.svg

dashboards:
  - apm-log-monitoring