name: Preview links

on:
  pull_request_target:
    branches:
      - main

defaults:
  run:
    working-directory: utils

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      - name: Create preview links
        id: links
        run: |
          yarn create-preview-links ${{ github.event.pull_request.url }} ${{ github.event.pull_request.number }}

      - name: Comment 
        run: |
          if [[ -z '${{ steps.generate.outputs.comment }}' ]]; then
              echo "Detected comment, posting to pull request"
          gh pr comment ${{github.event.pull_request.number}} --body ${{ steps.links.outputs.comment }}
          fi
